/**
 * =============================================
 *  GRIDPULSE — Frontend Application
 *  AI-Powered Electricity Demand Intelligence
 * =============================================
 *
 *  Multi-page architecture:
 *  Each page is a separate HTML file. The shared
 *  shell (sidebar + header) is generated by this
 *  script. Page-specific content lives in a
 *  <template id="page-template"> in each HTML file.
 *
 *  Sections:
 *   1.  Configuration
 *   2.  Navigation Config
 *   3.  Mock / API Data Layer
 *   4.  Application State
 *   5.  Utility Functions
 *   6.  Risk Calculations
 *   7.  Shell Generation
 *   8.  Chart Setup & Rendering
 *   9.  Page Rendering Functions
 *  10.  What-If Simulation
 *  11.  Event Listeners
 *  12.  Page-Specific Initialization
 *  13.  Main Init
 */

// =============================================
// 1. CONFIGURATION
// =============================================

const CONFIG = {
    region: "Delhi NCR",
    capacity: 8500,
    modelVersion: "GridPulse Forecast v1.4",
    baseUrl: "http://localhost:8000/api",
    animationDuration: 1200,
    toastDuration: 3500,
};

/**
 * Toggle this flag to switch between mock data and real backend API.
 * When true  → uses mock data defined below.
 * When false → calls the real backend endpoints.
 */
const USE_MOCK_DATA = false;


// =============================================
// 2. NAVIGATION CONFIG
// =============================================

const NAV_ITEMS = [
    { id: "overview",  label: "Overview",     icon: "layout-dashboard", href: "index.html"    },
    { id: "forecast",  label: "Forecast",     icon: "trending-up",      href: "forecast.html" },
    { id: "risk",      label: "Grid Risk",    icon: "shield-alert",     href: "risk.html"     },
    { id: "whatif",    label: "What-If Lab",  icon: "flask-conical",    href: "whatif.html"   },
    { id: "weather",   label: "Weather",      icon: "cloud-sun",        href: "weather.html"  },
    { id: "insights",  label: "Insights",     icon: "lightbulb",        href: "insights.html" },
];

/**
 * Detect current page from the URL filename.
 */
function getCurrentPage() {
    const path = window.location.pathname;
    const file = path.split("/").pop().replace(".html", "").toLowerCase();
    const map = { "": "overview", "index": "overview" };
    return map[file] !== undefined ? map[file] : file;
}


// ===============================
// 3. API / MOCK DATA LAYER
// Replace these functions with
// real backend API calls.
// ===============================

/**
 * Generate realistic 24-hour forecast data with natural fluctuations.
 */
function generateForecastData() {
    const baseProfile = [
        4820, 4650, 4480, 4350, 4280, 4420, 4750, 5320,
        5980, 6540, 7120, 7680, 8050, 8280, 8470, 8420,
        8190, 7860, 7480, 7050, 6620, 6180, 5720, 5280
    ];
    const temps = [
        31, 30, 29, 28, 28, 29, 31, 33,
        35, 36, 37, 38, 38, 38, 38, 37,
        36, 35, 34, 33, 32, 32, 31, 31
    ];
    return baseProfile.map((predicted, i) => {
        const noise = (Math.random() - 0.5) * 160;
        const actual = i <= 15 ? Math.round(predicted + noise) : null;
        const band = Math.round(80 + Math.random() * 100);
        return {
            time: `${String(i).padStart(2, "0")}:00`,
            predicted,
            lower: predicted - band,
            upper: predicted + band,
            actual,
            temperature: temps[i],
        };
    });
}

const mockForecastData = {
    region: "Delhi NCR",
    capacity: 8500,
    currentLoad: 7820,
    peakDemand: 8470,
    peakTime: "15:00",
    forecast: generateForecastData(),
};

const mockWeatherData = {
    temperature: 38,
    feelsLike: 41,
    humidity: 61,
    condition: "Hot / Clear",
    solarGeneration: 620,
    wind: 12,
    cloudCover: 15,
    solarRadiation: 820,
};

const mockRiskData = {
    level: "HIGH",
    utilization: 99.6,
    peakTime: "15:00",
    factors: {
        temperature: "HIGH",
        demandGrowth: "MEDIUM",
        solarAvailability: "LOW",
        peakProximity: "HIGH",
    },
};

const mockInsightsData = [
    { id: 1, type: "critical", icon: "alert-triangle", title: "Peak Risk",
      text: "Tomorrow's forecast peak of 8,470 MW is approaching the available capacity margin of 8,500 MW. Consider preemptive load management.",
      timestamp: "20:15 IST", severity: "CRITICAL" },
    { id: 2, type: "warning", icon: "thermometer", title: "Weather Impact",
      text: "Elevated temperatures (+2.1\u00b0C above seasonal average) are contributing to higher afternoon demand. Temperature-driven load is estimated at +310 MW.",
      timestamp: "19:48 IST", severity: "WARNING" },
    { id: 3, type: "info", icon: "sun", title: "Solar Offset",
      text: "Projected solar generation of 620 MW partially offsets daytime demand, reducing net peak by approximately 7.3%.",
      timestamp: "19:30 IST", severity: "INFO" },
    { id: 4, type: "warning", icon: "clock", title: "Planning Signal",
      text: "Prepare additional capacity or demand response measures before the 14:00\u201316:00 demand window. Grid stress is expected to peak at 15:00.",
      timestamp: "19:12 IST", severity: "WARNING" },
];

const mockAlertsData = [
    { time: "08:42", title: "Demand spike detected", desc: "Load exceeded the expected range by 3.8%.", severity: "critical" },
    { time: "07:15", title: "Temperature anomaly", desc: "Forecast temperature +2.4\u00b0C above seasonal average.", severity: "warning" },
    { time: "Yesterday 18:20", title: "Peak demand recorded", desc: "8,310 MW \u2014 highest load in the past 48 hours.", severity: "info" },
];

const mockDemandDrivers = [
    { name: "Temperature", value: 310, unit: "MW" },
    { name: "Peak-hour pattern", value: 220, unit: "MW" },
    { name: "Previous-day demand", value: 160, unit: "MW" },
    { name: "Humidity", value: 85, unit: "MW" },
    { name: "Solar generation", value: -110, unit: "MW" },
];

// --- API Functions -------------------------------------------------------

function simulateLatency(ms) {
    // Artificial latency removed for faster page switching
    return Promise.resolve();
}

async function fetchForecast() {
    if (USE_MOCK_DATA) { await simulateLatency(300); return mockForecastData; }
    const res = await fetch(`${CONFIG.baseUrl}/forecast`);
    if (!res.ok) throw new Error("Forecast API failed");
    return await res.json();
}

async function fetchWeather() {
    if (USE_MOCK_DATA) return mockWeatherData;
    try {
        var r = await fetch(CONFIG.baseUrl + "/weather");
        if (!r.ok) throw new Error("API error");
        return await r.json();
    } catch (e) { console.error(e); return mockWeatherData; }
}

async function fetchMetrics() {
    if (USE_MOCK_DATA) return { maeMw: 142, rmseMw: 198, mapePct: 2.4, baselineMaeMw: 250, improvementPct: 40, errorBandMw: 120 };
    try {
        var r = await fetch(CONFIG.baseUrl + "/metrics");
        if (!r.ok) throw new Error("API error");
        return await r.json();
    } catch (e) {
        console.error("Failed to fetch metrics:", e);
        return { maeMw: 142, rmseMw: 198, mapePct: 2.4, baselineMaeMw: 250, improvementPct: 40, errorBandMw: 120 };
    }
}

async function fetchRisk() {
    if (USE_MOCK_DATA) { await simulateLatency(200); return mockRiskData; }
    const res = await fetch(`${CONFIG.baseUrl}/risk`);
    if (!res.ok) throw new Error("Risk API failed");
    return await res.json();
}

async function fetchInsights() {
    if (USE_MOCK_DATA) { await simulateLatency(250); return mockInsightsData; }
    const res = await fetch(`${CONFIG.baseUrl}/insights`);
    if (!res.ok) throw new Error("Insights API failed");
    return await res.json();
}

async function runWhatIfScenario(parameters) {
    if (USE_MOCK_DATA) { await simulateLatency(700); return calculateLocalWhatIf(parameters); }
    const res = await fetch(`${CONFIG.baseUrl}/what-if`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(parameters),
    });
    if (!res.ok) throw new Error("What-If API failed");
    return await res.json();
}


// =============================================
// 4. APPLICATION STATE
// =============================================

const appState = {
    currentPage: "overview",
    forecast: null,
    weather: null,
    risk: null,
    insights: null,
    scenario: null,
    charts: {},
};


// =============================================
// 5. UTILITY FUNCTIONS
// =============================================

function $(sel)  { return document.querySelector(sel); }
function $$(sel) { return document.querySelectorAll(sel); }

function formatNumber(num) {
    return num.toLocaleString("en-IN");
}

function animateNumber(el, target, duration, decimals) {
    duration = duration || CONFIG.animationDuration;
    decimals = decimals || 0;
    const startTime = performance.now();
    (function update(now) {
        const progress = Math.min((now - startTime) / duration, 1);
        const eased = 1 - Math.pow(1 - progress, 3);
        const current = target * eased;
        el.textContent = decimals > 0
            ? formatNumber(parseFloat(current.toFixed(decimals)))
            : formatNumber(Math.round(current));
        if (progress < 1) requestAnimationFrame(update);
    })(performance.now());
}

function showToast(message, type) {
    type = type || "info";
    const container = $("#toastContainer");
    if (!container) return;
    const iconMap = { success: "check-circle", error: "alert-circle", info: "info", warning: "alert-triangle" };
    const toast = document.createElement("div");
    toast.className = "toast " + type;
    toast.innerHTML =
        '<i data-lucide="' + iconMap[type] + '" class="toast-icon" aria-hidden="true"></i>' +
        '<span class="toast-text">' + message + '</span>';
    container.appendChild(toast);
    if (typeof lucide !== 'undefined') lucide.createIcons({ nodes: [toast] });
    setTimeout(function () {
        toast.classList.add("removing");
        setTimeout(function () { toast.remove(); }, 300);
    }, CONFIG.toastDuration);
}

function updateDateTime() {
    var now = new Date();
    var dateEl = $("#headerDate");
    var timeEl = $("#headerTime");
    if (dateEl) dateEl.textContent = now.toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "short", year: "numeric" });
    if (timeEl) timeEl.textContent = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false });
}

function drawSparkline(canvasId, data, color) {
    color = color || "#2dd4bf";
    var canvas = document.getElementById(canvasId);
    if (!canvas) return;
    var ctx = canvas.getContext("2d");
    var w = canvas.width, h = canvas.height;
    var dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr; canvas.height = h * dpr;
    canvas.style.width = w + "px"; canvas.style.height = h + "px";
    ctx.scale(dpr, dpr);
    ctx.clearRect(0, 0, w, h);
    var min = Math.min.apply(null, data), max = Math.max.apply(null, data);
    var range = max - min || 1, step = w / (data.length - 1);
    ctx.beginPath();
    data.forEach(function (val, i) {
        var x = i * step, y = h - ((val - min) / range) * (h - 4) - 2;
        i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
    });
    ctx.strokeStyle = color; ctx.lineWidth = 1.5; ctx.stroke();
    ctx.lineTo((data.length - 1) * step, h); ctx.lineTo(0, h); ctx.closePath();
    var grad = ctx.createLinearGradient(0, 0, 0, h);
    grad.addColorStop(0, color + "33"); grad.addColorStop(1, "transparent");
    ctx.fillStyle = grad; ctx.fill();
}


// =============================================
// 6. RISK CALCULATIONS
// =============================================

/**
 * Central risk calculation — used everywhere.
 * Do NOT duplicate this logic.
 */
function calculateRisk(utilization) {
    if (utilization > 100) return { level: "CRITICAL", class: "critical" };
    if (utilization >= 85)  return { level: "HIGH",     class: "high"     };
    if (utilization >= 70)  return { level: "WATCH",    class: "watch"    };
    return { level: "NORMAL", class: "normal" };
}

/**
 * Deterministic local what-if model.
 * Responds to all four slider inputs.
 */
function calculateLocalWhatIf(params) {
    var baselinePeak = 8470, baseTemp = 38, baseHumidity = 61, baseSolar = 620;
    var tempDelta     = (params.temperature - baseTemp) * 110;
    var humidityDelta = (params.humidity - baseHumidity) * 8;
    var solarDelta    = -(params.solarGeneration - baseSolar);
    var growthDelta   = baselinePeak * (params.demandGrowth / 100);
    var totalChange   = Math.round(tempDelta + humidityDelta + solarDelta + growthDelta);
    var simulatedPeak = baselinePeak + totalChange;
    var utilization   = parseFloat(((simulatedPeak / CONFIG.capacity) * 100).toFixed(1));
    var risk = calculateRisk(utilization);
    return {
        baselinePeak: baselinePeak,
        simulatedPeak: simulatedPeak,
        change: totalChange,
        utilization: utilization,
        risk: risk.level,
        riskClass: risk.class,
        forecast: mockForecastData.forecast.map(function (row) {
            var hourFactor = row.predicted / baselinePeak;
            return Object.assign({}, row, { simulated: Math.round(row.predicted + totalChange * hourFactor) });
        }),
    };
}


// =============================================
// 7. SHELL GENERATION
// =============================================

/**
 * Build the app shell: sidebar, header, page container.
 * Extracts <template id="page-template"> content and injects it.
 */
function buildAppShell() {
    var page = getCurrentPage();
    appState.currentPage = page;
    var app = document.getElementById("app");
    if (!app) return;

    // --- Sidebar nav items ---
    var navHTML = NAV_ITEMS.map(function (item) {
        var isActive = item.id === page;
        return '<li>' +
            '<a href="' + item.href + '" class="nav-item' + (isActive ? ' active' : '') + '" data-page="' + item.id + '"' +
            (isActive ? ' aria-current="page"' : '') + '>' +
            '<span class="nav-indicator" aria-hidden="true"></span>' +
            '<i data-lucide="' + item.icon + '" aria-hidden="true"></i>' +
            '<span>' + item.label + '</span>' +
            '</a></li>';
    }).join("");

    // --- Build shell ---
    app.innerHTML =
        /* Mobile overlay */
        '<div class="mobile-overlay" id="mobileOverlay" aria-hidden="true"></div>' +

        /* Sidebar */
        '<aside class="sidebar" id="sidebar" role="navigation" aria-label="Main navigation">' +
            '<div class="sidebar-brand">' +
                '<div class="brand-icon" aria-hidden="true">' +
                    '<svg viewBox="0 0 32 32" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' +
                        '<path d="M13 2L4 17h9l-2 13 11-17h-9l4-11z" fill="rgba(45,212,191,0.15)" stroke="var(--cyan)"/>' +
                        '<circle cx="16" cy="16" r="14" stroke="var(--cyan)" opacity="0.3"/>' +
                        '<line x1="2" y1="16" x2="6" y2="16" stroke="var(--cyan)" opacity="0.2"/>' +
                        '<line x1="26" y1="16" x2="30" y2="16" stroke="var(--cyan)" opacity="0.2"/>' +
                        '<line x1="16" y1="2" x2="16" y2="6" stroke="var(--cyan)" opacity="0.2"/>' +
                        '<line x1="16" y1="26" x2="16" y2="30" stroke="var(--cyan)" opacity="0.2"/>' +
                    '</svg>' +
                '</div>' +
                '<div class="brand-text">' +
                    '<span class="brand-name">GRIDPULSE</span>' +
                    '<span class="brand-tagline">Demand Intelligence</span>' +
                '</div>' +
            '</div>' +
            '<nav class="sidebar-nav" aria-label="Page navigation">' +
                '<ul class="nav-list" role="list">' + navHTML + '</ul>' +
            '</nav>' +
            '<div class="sidebar-footer">' +
                '<div class="system-status">' +
                    '<div class="status-header">SYSTEM STATUS</div>' +
                    '<div class="status-row">' +
                        '<span class="status-dot operational" aria-label="Operational"></span>' +
                        '<span class="status-text">All systems operational</span>' +
                    '</div>' +
                    '<div class="status-meta">' +
                        '<div class="status-meta-row"><span class="status-label">Model</span><span class="status-value">GridPulse Forecast v1.4</span></div>' +
                        '<div class="status-meta-row"><span class="status-label">Updated</span><span class="status-value" id="lastUpdatedTime">20:25 IST</span></div>' +
                    '</div>' +
                '</div>' +
                '<div class="operator-badge">' +
                    '<div class="operator-avatar" aria-hidden="true"><i data-lucide="user" aria-hidden="true"></i></div>' +
                    '<div class="operator-info"><span class="operator-name">Grid Operator</span><span class="operator-role">Control Center</span></div>' +
                '</div>' +
            '</div>' +
        '</aside>' +

        /* Main workspace */
        '<main class="main-workspace" id="mainWorkspace">' +
            '<header class="top-header" role="banner">' +
                '<div class="header-left">' +
                    '<button class="mobile-menu-btn" id="mobileMenuBtn" aria-label="Open navigation menu">' +
                        '<i data-lucide="menu" aria-hidden="true"></i>' +
                    '</button>' +
                    '<div class="header-title-group">' +
                        '<h1 class="header-region">DELHI NCR GRID</h1>' +
                        '<div class="header-status">' +
                            '<span class="live-pulse" aria-hidden="true"></span>' +
                            '<span class="live-text">LIVE SIMULATION</span>' +
                            '<span class="simulation-badge">Hackathon Demo</span>' +
                        '</div>' +
                    '</div>' +
                '</div>' +
                '<div class="header-right">' +
                    '<div class="header-datetime">' +
                        '<span class="header-date" id="headerDate"></span>' +
                        '<span class="header-time" id="headerTime"></span>' +
                    '</div>' +
                    '<div class="header-actions">' +
                        '<button class="header-btn" id="refreshBtn" aria-label="Refresh data" title="Refresh data"><i data-lucide="refresh-cw" aria-hidden="true"></i></button>' +
                        '<button class="header-btn" id="notifBtn" aria-label="Notifications" title="Notifications"><i data-lucide="bell" aria-hidden="true"></i><span class="notif-badge" aria-label="3 notifications">3</span></button>' +
                        '<button class="header-btn" id="settingsBtn" aria-label="Settings" title="Settings"><i data-lucide="settings" aria-hidden="true"></i></button>' +
                    '</div>' +
                '</div>' +
            '</header>' +
            '<div class="page-container" id="pageContainer"></div>' +
        '</main>';

    // --- Insert page-specific content from <template> ---
    var template = document.getElementById("page-template");
    var container = document.getElementById("pageContainer");
    if (template && container) {
        container.appendChild(template.content.cloneNode(true));
    }

    // --- Toast container ---
    if (!document.getElementById("toastContainer")) {
        var toast = document.createElement("div");
        toast.className = "toast-container";
        toast.id = "toastContainer";
        toast.setAttribute("aria-live", "polite");
        toast.setAttribute("aria-atomic", "true");
        document.body.appendChild(toast);
    }
}


// =============================================
// 8. CHART SETUP & RENDERING
// =============================================

// Chart.js defaults
Chart.defaults.color = "#8899b4";
Chart.defaults.borderColor = "#1e2940";
Chart.defaults.font.family = "'Inter', sans-serif";
Chart.defaults.font.size = 11;
Chart.defaults.plugins.legend.labels.usePointStyle = true;
Chart.defaults.plugins.legend.labels.pointStyleWidth = 8;
Chart.defaults.plugins.legend.labels.padding = 16;
Chart.defaults.plugins.tooltip.backgroundColor = "rgba(15, 20, 32, 0.95)";
Chart.defaults.plugins.tooltip.borderColor = "#1e2940";
Chart.defaults.plugins.tooltip.borderWidth = 1;
Chart.defaults.plugins.tooltip.padding = 12;
Chart.defaults.plugins.tooltip.cornerRadius = 8;
Chart.defaults.plugins.tooltip.titleFont = { weight: "600" };
Chart.defaults.scale.grid = { color: "rgba(30, 41, 64, 0.6)" };

function renderOverviewChart(forecastData) {
    var ctx = document.getElementById("overviewChart");
    if (!ctx) return;
    if (appState.charts.overview) appState.charts.overview.destroy();
    var data = forecastData.forecast;
    var labels = data.map(function (d) { return d.time; });
    appState.charts.overview = new Chart(ctx, {
        type: "line",
        data: {
            labels: labels,
            datasets: [
                { label: "Actual Demand", data: data.map(function (d) { return d.actual; }),
                  borderColor: "#2dd4bf", backgroundColor: "rgba(45,212,191,0.08)", borderWidth: 2.5,
                  pointRadius: 0, pointHoverRadius: 5, pointHoverBackgroundColor: "#2dd4bf",
                  tension: 0.35, fill: false, spanGaps: false },
                { label: "Predicted Demand", data: data.map(function (d) { return d.predicted; }),
                  borderColor: "#a78bfa", borderWidth: 2, borderDash: [6, 3],
                  pointRadius: 0, pointHoverRadius: 5, pointHoverBackgroundColor: "#a78bfa",
                  tension: 0.35, fill: false },
                { label: "Confidence (Upper)", data: data.map(function (d) { return d.upper; }),
                  borderColor: "transparent", backgroundColor: "rgba(167,139,250,0.1)",
                  pointRadius: 0, tension: 0.35, fill: "+1" },
                { label: "Confidence (Lower)", data: data.map(function (d) { return d.lower; }),
                  borderColor: "transparent", backgroundColor: "rgba(167,139,250,0.1)",
                  pointRadius: 0, tension: 0.35, fill: false },
            ],
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            interaction: { mode: "index", intersect: false },
            plugins: {
                legend: { display: true, position: "top", align: "end",
                    labels: { filter: function (item) { return item.text !== "Confidence (Upper)" && item.text !== "Confidence (Lower)"; } } },
                tooltip: { callbacks: {
                    title: function (items) { return "Time: " + items[0].label; },
                    afterTitle: function (items) { var row = data[items[0].dataIndex]; return "Temperature: " + row.temperature + "\u00b0C"; },
                    label: function (ctx) { var v = ctx.parsed.y; if (v == null) return null; return ctx.dataset.label + ": " + formatNumber(v) + " MW (" + ((v / CONFIG.capacity) * 100).toFixed(1) + "%)"; }
                }},
                annotation: { annotations: {
                    capacityLine: { type: "line", yMin: CONFIG.capacity, yMax: CONFIG.capacity,
                        borderColor: "rgba(239,68,68,0.5)", borderWidth: 2, borderDash: [8, 4],
                        label: { display: true, content: "Capacity: " + formatNumber(CONFIG.capacity) + " MW", position: "start",
                            backgroundColor: "rgba(239,68,68,0.15)", color: "#ef4444", font: { size: 10, weight: "600" }, padding: { top: 2, bottom: 2, left: 6, right: 6 } } },
                    peakPoint: { type: "point", xValue: "15:00", yValue: 8470,
                        backgroundColor: "rgba(239,68,68,0.3)", borderColor: "#ef4444", borderWidth: 2, radius: 7,
                        label: { display: true, content: "Peak: 8,470 MW", position: { x: "start", y: "start" },
                            backgroundColor: "rgba(239,68,68,0.15)", color: "#ef4444", font: { size: 10, weight: "600" },
                            padding: { top: 2, bottom: 2, left: 6, right: 6 }, xAdjust: -10, yAdjust: -20 } }
                }}
            },
            scales: { x: { ticks: { maxTicksLimit: 12 } }, y: { min: 3500, max: 9500, ticks: { callback: function (v) { return formatNumber(v) + " MW"; }, maxTicksLimit: 8 } } }
        }
    });
}

function renderForecastChart(forecastData) {
    var ctx = document.getElementById("forecastChart");
    if (!ctx) return;
    if (appState.charts.forecast) appState.charts.forecast.destroy();
    var data = forecastData.forecast;
    appState.charts.forecast = new Chart(ctx, {
        type: "line",
        data: {
            labels: data.map(function (d) { return d.time; }),
            datasets: [
                { label: "Actual Demand", data: data.map(function (d) { return d.actual; }),
                  borderColor: "#2dd4bf", borderWidth: 2.5, pointRadius: 2, pointHoverRadius: 5,
                  pointBackgroundColor: "#2dd4bf", tension: 0.35, fill: false, spanGaps: false },
                { label: "Predicted Demand", data: data.map(function (d) { return d.predicted; }),
                  borderColor: "#a78bfa", borderWidth: 2, borderDash: [6, 3], pointRadius: 2,
                  pointHoverRadius: 5, pointBackgroundColor: "#a78bfa", tension: 0.35, fill: false },
                { label: "Upper Bound", data: data.map(function (d) { return d.upper; }),
                  borderColor: "transparent", backgroundColor: "rgba(167,139,250,0.08)",
                  pointRadius: 0, tension: 0.35, fill: "+1" },
                { label: "Lower Bound", data: data.map(function (d) { return d.lower; }),
                  borderColor: "transparent", pointRadius: 0, tension: 0.35, fill: false },
            ],
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            interaction: { mode: "index", intersect: false },
            plugins: {
                legend: { display: true, position: "top", align: "end",
                    labels: { filter: function (i) { return i.text !== "Upper Bound" && i.text !== "Lower Bound"; } } },
                tooltip: { callbacks: { label: function (c) { var v = c.parsed.y; if (v == null) return null; return c.dataset.label + ": " + formatNumber(v) + " MW"; } } },
                annotation: { annotations: { capacityLine: { type: "line", yMin: CONFIG.capacity, yMax: CONFIG.capacity,
                    borderColor: "rgba(239,68,68,0.5)", borderWidth: 2, borderDash: [8, 4],
                    label: { display: true, content: "Capacity: " + formatNumber(CONFIG.capacity) + " MW", position: "start",
                        backgroundColor: "rgba(239,68,68,0.15)", color: "#ef4444", font: { size: 10, weight: "600" }, padding: 4 } } } }
            },
            scales: { x: { ticks: { maxTicksLimit: 12 } }, y: { min: 3500, max: 9500, ticks: { callback: function (v) { return formatNumber(v) + " MW"; }, maxTicksLimit: 8 } } }
        }
    });
}

function renderWhatIfChart(scenarioData) {
    var ctx = document.getElementById("whatifChart");
    if (!ctx) return;
    if (appState.charts.whatif) appState.charts.whatif.destroy();
    var data = scenarioData.forecast;
    appState.charts.whatif = new Chart(ctx, {
        type: "line",
        data: {
            labels: data.map(function (d) { return d.time; }),
            datasets: [
                { label: "Baseline", data: data.map(function (d) { return d.predicted; }),
                  borderColor: "#5a6a85", borderWidth: 2, borderDash: [6, 3], pointRadius: 0, pointHoverRadius: 4, tension: 0.35, fill: false },
                { label: "Simulated", data: data.map(function (d) { return d.simulated; }),
                  borderColor: "#2dd4bf", borderWidth: 2.5, pointRadius: 0, pointHoverRadius: 5,
                  pointHoverBackgroundColor: "#2dd4bf", tension: 0.35, fill: false },
            ],
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            interaction: { mode: "index", intersect: false },
            plugins: {
                legend: { display: true, position: "top", align: "end" },
                tooltip: { callbacks: { label: function (c) { return c.dataset.label + ": " + formatNumber(c.parsed.y) + " MW"; } } },
                annotation: { annotations: { capacityLine: { type: "line", yMin: CONFIG.capacity, yMax: CONFIG.capacity,
                    borderColor: "rgba(239,68,68,0.5)", borderWidth: 2, borderDash: [8, 4],
                    label: { display: true, content: "Capacity: " + formatNumber(CONFIG.capacity) + " MW", position: "start",
                        backgroundColor: "rgba(239,68,68,0.15)", color: "#ef4444", font: { size: 10, weight: "600" }, padding: 4 } } } }
            },
            scales: { x: { ticks: { maxTicksLimit: 12 } }, y: { min: 3500, max: 10000, ticks: { callback: function (v) { return formatNumber(v) + " MW"; }, maxTicksLimit: 8 } } }
        }
    });
}

function renderRiskGauge(utilization) {
    var canvas = document.getElementById("riskGauge");
    if (!canvas) return;
    var ctx = canvas.getContext("2d");
    var dpr = window.devicePixelRatio || 1;
    var w = 280, h = 180;
    canvas.width = w * dpr; canvas.height = h * dpr;
    canvas.style.width = w + "px"; canvas.style.height = h + "px";
    ctx.scale(dpr, dpr); ctx.clearRect(0, 0, w, h);
    var cx = w / 2, cy = h - 20, radius = 110, lw = 16;
    var startA = Math.PI, endA = 2 * Math.PI;
    ctx.beginPath(); ctx.arc(cx, cy, radius, startA, endA);
    ctx.strokeStyle = "#1e2940"; ctx.lineWidth = lw; ctx.lineCap = "round"; ctx.stroke();
    var segs = [{ e: 0.7, c: "#22c55e" }, { e: 0.85, c: "#ffb74d" }, { e: 1.0, c: "#e67e22" }, { e: 1.15, c: "#ef4444" }];
    var prev = 0;
    segs.forEach(function (s) {
        ctx.beginPath(); ctx.arc(cx, cy, radius, startA + (endA - startA) * (prev / 1.15), startA + (endA - startA) * (s.e / 1.15));
        ctx.strokeStyle = s.c; ctx.lineWidth = lw; ctx.lineCap = "butt"; ctx.stroke(); prev = s.e;
    });
    var clamped = Math.min(utilization, 115) / 115;
    var na = startA + (endA - startA) * clamped;
    ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(cx + Math.cos(na) * (radius - 25), cy + Math.sin(na) * (radius - 25));
    ctx.strokeStyle = "#e8ecf4"; ctx.lineWidth = 2.5; ctx.lineCap = "round"; ctx.stroke();
    ctx.beginPath(); ctx.arc(cx, cy, 5, 0, 2 * Math.PI); ctx.fillStyle = "#e8ecf4"; ctx.fill();
}

function renderOffsetDonut(solar, gross) {
    var canvas = document.getElementById("offsetDonut");
    if (!canvas) return;
    var ctx = canvas.getContext("2d"), dpr = window.devicePixelRatio || 1, size = 140;
    canvas.width = size * dpr; canvas.height = size * dpr;
    canvas.style.width = size + "px"; canvas.style.height = size + "px";
    ctx.scale(dpr, dpr); ctx.clearRect(0, 0, size, size);
    var cx = size / 2, cy = size / 2, r = 52, lw = 14, pct = solar / gross;
    ctx.beginPath(); ctx.arc(cx, cy, r, 0, 2 * Math.PI); ctx.strokeStyle = "#1e2940"; ctx.lineWidth = lw; ctx.stroke();
    ctx.beginPath(); ctx.arc(cx, cy, r, -Math.PI / 2, -Math.PI / 2 + 2 * Math.PI * pct);
    ctx.strokeStyle = "#22c55e"; ctx.lineWidth = lw; ctx.lineCap = "round"; ctx.stroke();
    ctx.fillStyle = "#e8ecf4"; ctx.font = "bold 16px 'JetBrains Mono', monospace";
    ctx.textAlign = "center"; ctx.textBaseline = "middle";
    ctx.fillText((pct * 100).toFixed(1) + "%", cx, cy - 6);
    ctx.font = "10px 'Inter', sans-serif"; ctx.fillStyle = "#5a6a85"; ctx.fillText("Solar", cx, cy + 12);
}

function renderWeatherTempChart(forecastData) {
    var ctx = document.getElementById("weatherTempChart");
    if (!ctx) return;
    if (appState.charts.weatherTemp) appState.charts.weatherTemp.destroy();
    var data = forecastData.forecast;
    appState.charts.weatherTemp = new Chart(ctx, {
        type: "line",
        data: {
            labels: data.map(function (d) { return d.time; }),
            datasets: [{ label: "Temperature (\u00b0C)", data: data.map(function (d) { return d.temperature; }),
                borderColor: "#ffb74d", backgroundColor: "rgba(255,183,77,0.1)", borderWidth: 2.5,
                pointRadius: 3, pointBackgroundColor: "#ffb74d", tension: 0.4, fill: true }],
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: true, position: "top", align: "end" } },
            scales: { x: { ticks: { maxTicksLimit: 12 } }, y: { min: 25, max: 45, ticks: { callback: function (v) { return v + "\u00b0C"; } } } }
        }
    });
}

function renderDemandTempChart(forecastData) {
    var ctx = document.getElementById("demandTempChart");
    if (!ctx) return;
    if (appState.charts.demandTemp) appState.charts.demandTemp.destroy();
    var pts = forecastData.forecast.map(function (d) { return { x: d.temperature, y: d.predicted }; });
    appState.charts.demandTemp = new Chart(ctx, {
        type: "scatter",
        data: { datasets: [{ label: "Demand vs Temperature", data: pts,
            backgroundColor: "rgba(45,212,191,0.5)", borderColor: "#2dd4bf", borderWidth: 1, pointRadius: 6, pointHoverRadius: 8 }] },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: true, position: "top", align: "end" },
                tooltip: { callbacks: { label: function (c) { return c.parsed.x + "\u00b0C \u2192 " + formatNumber(c.parsed.y) + " MW"; } } } },
            scales: {
                x: { title: { display: true, text: "Temperature (\u00b0C)", color: "#8899b4" }, min: 25, max: 42 },
                y: { title: { display: true, text: "Demand (MW)", color: "#8899b4" }, min: 3500, max: 9500, ticks: { callback: function (v) { return formatNumber(v); } } }
            }
        }
    });
}


// =============================================
// 9. PAGE RENDERING FUNCTIONS
// =============================================

function renderKPIs(forecast, risk) {
    var loadEl = document.querySelector("#kpi-load .kpi-number");
    if (loadEl) animateNumber(loadEl, forecast.currentLoad);
    var peakEl = document.querySelector("#kpi-peak .kpi-number");
    if (peakEl) animateNumber(peakEl, forecast.peakDemand);
    var utilPct = parseFloat(((forecast.peakDemand / forecast.capacity) * 100).toFixed(1));
    var utilEl = document.querySelector("#kpi-util .kpi-number");
    if (utilEl) animateNumber(utilEl, utilPct, CONFIG.animationDuration, 1);
    setTimeout(function () { var bar = $("#utilProgress"); if (bar) bar.style.width = Math.min(utilPct, 100) + "%"; }, 100);
    var riskResult = calculateRisk(utilPct);
    var badge = $("#riskBadge");
    if (badge) { badge.textContent = riskResult.level; badge.className = "risk-badge " + riskResult.class; }
    setTimeout(function () { var fill = $("#riskFill"); if (fill) fill.style.width = Math.min(utilPct, 100) + "%"; }, 100);
    var actuals = forecast.forecast.map(d => d.actual).filter(v => v !== null);
    if (actuals.length === 0) actuals = forecast.forecast.map(d => d.predicted).slice(0, 8);
    var predicted = forecast.forecast.map(d => d.predicted);
    drawSparkline("sparkLoad", actuals, "#2dd4bf");
    drawSparkline("sparkPeak", predicted, "#a78bfa");
}

function renderDemandDrivers() {
    var container = $("#driversList");
    // The backend does not provide demand drivers. Clear the container or show a message.
    container.innerHTML = '<div style="padding:1rem;color:var(--text-muted);text-align:center;font-size:0.875rem;">Model drivers are currently computed in the backend ML layer and not exposed via API.</div>';
}

function renderAlerts() {
    var container = $("#alertsList");
    // The backend does not provide historical alerts in the current API version.
    container.innerHTML = '<div style="padding:1rem;color:var(--text-muted);text-align:center;font-size:0.875rem;">No active grid alerts from the backend.</div>';
}

function renderForecastTable(forecastData) {
    var tbody = $("#forecastTableBody");
    if (!tbody) return;
    tbody.innerHTML = forecastData.forecast.map(function (row) {
        var util = ((row.predicted / CONFIG.capacity) * 100).toFixed(1);
        var risk = calculateRisk(parseFloat(util));
        return '<tr><td>' + row.time + '</td><td>' + formatNumber(row.predicted) + ' MW</td><td>' + formatNumber(row.lower) + ' MW</td><td>' +
            formatNumber(row.upper) + ' MW</td><td>' + row.temperature + '\u00b0C</td><td>' + util + '%</td><td class="risk-cell ' + risk.class + '">' + risk.level + '</td></tr>';
    }).join("");
}

function renderRiskFactors(riskData) {
    var container = $("#riskFactorsGrid");
    if (!container) return;
    var factors = [
        { name: "Temperature", level: riskData.factors.temperature, icon: "thermometer", desc: "High temperatures drive increased cooling demand across the grid." },
        { name: "Demand Growth", level: riskData.factors.demandGrowth, icon: "trending-up", desc: "Day-over-day demand growth is within moderate range." },
        { name: "Solar Availability", level: riskData.factors.solarAvailability, icon: "sun", desc: "Current solar generation partially offsets peak demand." },
        { name: "Peak Proximity", level: riskData.factors.peakProximity, icon: "clock", desc: "The grid is approaching or within the daily peak demand window." },
    ];
    container.innerHTML = factors.map(function (f) {
        var col = f.level === "HIGH" ? "var(--red)" : f.level === "MEDIUM" ? "var(--amber)" : "var(--green)";
        return '<div class="risk-factor-card"><i data-lucide="' + f.icon + '" class="risk-factor-icon" aria-hidden="true" style="color:' + col + '"></i>' +
            '<div class="risk-factor-name">' + f.name + '</div><span class="risk-factor-level ' + f.level.toLowerCase() + '">' + f.level + '</span>' +
            '<p class="risk-factor-desc">' + f.desc + '</p></div>';
    }).join("");
    if (typeof lucide !== 'undefined') lucide.createIcons({ nodes: [container] });
}

function renderRiskTimeline() {
    var container = $("#riskTimeline");
    if (!container) return;
    if (!appState.risk || !appState.risk.hourly) return;
    
    // Group hourly data into 4-hour segments for the timeline
    var hourly = appState.risk.hourly;
    var segs = [];
    for (var i = 0; i < hourly.length; i += 4) {
        var chunk = hourly.slice(i, i + 4);
        var maxDemand = Math.max.apply(null, chunk.map(c => c.demand));
        var maxTemp = Math.max.apply(null, chunk.map(c => c.temperature));
        var maxUtil = Math.max.apply(null, chunk.map(c => c.utilization));
        var riskLevel = calculateRisk(maxUtil).level;
        segs.push({
            start: chunk[0].time,
            end: i + 4 < hourly.length ? hourly[i + 4].time : "24:00",
            demand: maxDemand,
            temp: maxTemp,
            risk: riskLevel,
            util: maxUtil.toFixed(1)
        });
    }

    container.innerHTML = segs.map(function (s) {
        return '<div class="timeline-segment ' + s.risk.toLowerCase() + '" data-start="' + s.start + '" data-end="' + s.end +
            '" data-demand="' + s.demand + '" data-temp="' + s.temp + '" data-util="' + s.util + '" data-risk="' + s.risk +
            '" role="button" tabindex="0" aria-label="' + s.start + ' to ' + s.end + ': ' + s.risk + '">' +
            '<span class="timeline-label">' + s.risk + '</span><span class="timeline-time">' + s.start + '\u2013' + s.end + '</span></div>';
    }).join("");

    var segments = container.querySelectorAll(".timeline-segment");
    var tooltip = document.getElementById("timelineTooltip");
    if (!tooltip) {
        tooltip = document.createElement("div");
        tooltip.id = "timelineTooltip";
        tooltip.className = "timeline-tooltip";
        container.appendChild(tooltip);
    }
    segments.forEach(function (seg) {
        function show(e) {
            var rect = seg.getBoundingClientRect(), pr = container.getBoundingClientRect();
            tooltip.innerHTML = '<div class="tt-header">' + seg.dataset.start + ' \u2013 ' + seg.dataset.end + '</div>' +
                '<div class="tt-row"><span class="tt-label">Peak Demand</span><span class="tt-value">' + formatNumber(parseFloat(seg.dataset.demand)) + ' MW</span></div>' +
                '<div class="tt-row"><span class="tt-label">Capacity</span><span class="tt-value">' + formatNumber(CONFIG.capacity) + ' MW</span></div>' +
                '<div class="tt-row"><span class="tt-label">Utilization</span><span class="tt-value">' + seg.dataset.util + '%</span></div>' +
                '<div class="tt-row"><span class="tt-label">Risk</span><span class="tt-value">' + seg.dataset.risk + '</span></div>' +
                '<div class="tt-row"><span class="tt-label">Temperature</span><span class="tt-value">' + seg.dataset.temp + '\u00b0C</span></div>';
            tooltip.style.left = (rect.left - pr.left + rect.width / 2) + "px";
            tooltip.style.top = "-90px";
            tooltip.classList.add("visible");
        }
        function hide() { tooltip.classList.remove("visible"); }
        seg.addEventListener("mouseenter", show); seg.addEventListener("mouseleave", hide);
        seg.addEventListener("focus", show); seg.addEventListener("blur", hide);
    });
}

function renderRiskPage(riskData) {
    var utilPct = riskData.utilization, risk = calculateRisk(utilPct);
    var badgeLg = $("#riskBadgeLg");
    if (badgeLg) { badgeLg.textContent = risk.level + " RISK"; badgeLg.className = "risk-badge-lg " + risk.class; }
    var riskUtil = $("#riskUtil"); if (riskUtil) riskUtil.textContent = utilPct + "%";
    var riskPeak = $("#riskPeak"); if (riskPeak) riskPeak.textContent = formatNumber(riskData.peakDemand) + " MW";
    var gaugeVal = $("#gaugeValue"); if (gaugeVal) gaugeVal.textContent = utilPct + "%";
    renderRiskGauge(utilPct);
    renderRiskFactors(riskData);
    renderRiskTimeline();
}

function renderInsights(insights) {
    var container = $("#insightsGrid");
    if (!container) return;
    var tm = { critical: { ic: "critical", sv: "CRITICAL" }, warning: { ic: "warning", sv: "WARNING" }, info: { ic: "info", sv: "INFO" }, success: { ic: "success", sv: "OK" } };
    container.innerHTML = insights.map(function (ins) {
        var t = tm[ins.type] || tm.info;
        return '<div class="insight-card"><div class="insight-header"><div class="insight-icon-wrap ' + t.ic + '">' +
            '<i data-lucide="' + ins.icon + '" aria-hidden="true"></i></div>' +
            '<span class="insight-severity ' + t.ic + '">' + t.sv + '</span></div>' +
            '<h3 class="insight-title">' + ins.title + '</h3><p class="insight-text">' + ins.text + '</p>' +
            '<div class="insight-footer"><span class="insight-timestamp">' + ins.timestamp + '</span>' +
            '<span class="insight-source">MODEL-GENERATED INSIGHT</span></div></div>';
    }).join("");
    lucide.createIcons({ nodes: [container] });
}

function renderWeatherSparkline() {
    if (appState.forecast && appState.forecast.forecast) {
        var temps = appState.forecast.forecast.map(d => d.temperature);
        drawSparkline("weatherSparkline", temps, "#ffb74d");
    }
}

function updateOverviewDOMValues(forecast, weather) {
    var kpiPeakTime = $("#kpiPeakTime"); if (kpiPeakTime) kpiPeakTime.textContent = forecast.peakTime ? forecast.peakTime.substring(11, 16) : "15:00";
    var kpiCapacity = $("#kpiCapacity"); if (kpiCapacity) kpiCapacity.textContent = formatNumber(CONFIG.capacity) + " MW";
    var peakStatCapacity = $("#peakStatCapacity"); if (peakStatCapacity) peakStatCapacity.textContent = formatNumber(CONFIG.capacity) + " MW";
    
    var peakTimeRange = $("#peakTimeRange");
    if (peakTimeRange && forecast.peakTime) {
        try {
            var pt = new Date(forecast.peakTime);
            pt.setHours(pt.getHours() - 1); var start = pt.toTimeString().substring(0, 5);
            pt.setHours(pt.getHours() + 2); var end = pt.toTimeString().substring(0, 5);
            peakTimeRange.textContent = start + " \u2014 " + end;
        } catch(e) { console.error(e); }
    }
    
    var peakStatPeak = $("#peakStatPeak"); if (peakStatPeak) peakStatPeak.textContent = formatNumber(forecast.peakDemand) + " MW";
    var peakStatUtil = $("#peakStatUtil"); if (peakStatUtil) peakStatUtil.textContent = ((forecast.peakDemand / CONFIG.capacity) * 100).toFixed(1) + "%";
    
    var riskResult = calculateRisk((forecast.peakDemand / CONFIG.capacity) * 100);
    var peakStatStatus = $("#peakStatStatus"); 
    if (peakStatStatus) {
        peakStatStatus.textContent = riskResult.level + " RISK";
        peakStatStatus.className = "peak-stat-value risk-text " + riskResult.class;
    }
    
    var weatherTemp = $("#weatherTemp"); if (weatherTemp) weatherTemp.textContent = weather.temperature + "\u00b0C";
    var weatherFeels = $("#weatherFeels"); if (weatherFeels) weatherFeels.textContent = weather.feelsLike + "\u00b0C";
    var weatherHumidity = $("#weatherHumidity"); if (weatherHumidity) weatherHumidity.textContent = weather.humidity + "%";
    var weatherCondition = $("#weatherCondition"); if (weatherCondition) weatherCondition.textContent = weather.condition;
    
    var offsetGross = $("#offsetGross"); if (offsetGross) offsetGross.textContent = formatNumber(forecast.peakDemand) + " MW";
    var offsetSolar = $("#offsetSolar"); if (offsetSolar) offsetSolar.textContent = formatNumber(weather.solarGeneration) + " MW";
    var offsetNet = $("#offsetNet"); if (offsetNet) offsetNet.textContent = formatNumber(forecast.peakDemand - weather.solarGeneration) + " MW";
    var offsetPercent = $("#offsetPercent"); if (offsetPercent) offsetPercent.textContent = ((weather.solarGeneration / forecast.peakDemand) * 100).toFixed(1) + "%";
}

function updateWeatherPageDOMValues(weather) {
    var weatherPageTemp = $("#weatherPageTemp"); if (weatherPageTemp) weatherPageTemp.textContent = weather.temperature + "\u00b0C";
    var weatherPageCondition = $("#weatherPageCondition"); if (weatherPageCondition) weatherPageCondition.textContent = weather.condition;
    var weatherPageFeels = $("#weatherPageFeels"); if (weatherPageFeels) weatherPageFeels.textContent = "Feels like " + weather.feelsLike + "\u00b0C";
    var weatherPageHumidity = $("#weatherPageHumidity"); if (weatherPageHumidity) weatherPageHumidity.textContent = weather.humidity + "%";
    var weatherPageWind = $("#weatherPageWind"); if (weatherPageWind) weatherPageWind.textContent = weather.wind + " km/h";
    var weatherPageCloud = $("#weatherPageCloud"); if (weatherPageCloud) weatherPageCloud.textContent = weather.cloudCover + "%";
    var weatherPageSolar = $("#weatherPageSolar"); if (weatherPageSolar) weatherPageSolar.textContent = weather.solarRadiation + " W/m\u00b2";
}

function updateForecastPageDOMValues(metrics) {
    var metricMae = $("#metricMae"); if (metricMae) metricMae.innerHTML = metrics.maeMw.toFixed(0) + " <small>MW</small>";
    var metricRmse = $("#metricRmse"); if (metricRmse) metricRmse.innerHTML = metrics.rmseMw.toFixed(0) + " <small>MW</small>";
    var metricMape = $("#metricMape"); if (metricMape) metricMape.innerHTML = metrics.mapePct.toFixed(1) + "<small>%</small>";
    var metricPeakError = $("#metricPeakError"); 
    if (metricPeakError) {
        metricPeakError.innerHTML = ((metrics.errorBandMw / CONFIG.capacity) * 100).toFixed(1) + "<small>%</small>";
    }
}


// =============================================
// 10. WHAT-IF SIMULATION
// =============================================

function getSliderValues() {
    return {
        temperature: parseFloat($("#sliderTemp").value),
        humidity: parseFloat($("#sliderHumidity").value),
        solarGeneration: parseFloat($("#sliderSolar").value),
        demandGrowth: parseFloat($("#sliderGrowth").value),
    };
}

function updateSliderDisplay() {
    var v = getSliderValues();
    $("#sliderTempVal").textContent     = v.temperature + "\u00b0C";
    $("#sliderHumidityVal").textContent = v.humidity + "%";
    $("#sliderSolarVal").textContent    = formatNumber(v.solarGeneration) + " MW";
    $("#sliderGrowthVal").textContent   = (v.demandGrowth >= 0 ? "+" : "") + v.demandGrowth + "%";
}

async function executeSimulation() {
    var btn = $("#runSimBtn"), btnSpan = btn.querySelector("span"), btnIcon = btn.querySelector("i");
    btn.classList.add("loading"); btn.disabled = true;
    btnSpan.textContent = "ANALYZING...";
    if (btnIcon) btnIcon.setAttribute("data-lucide", "loader");
    if (typeof lucide !== 'undefined') { try { lucide.createIcons({ nodes: [btn] }); } catch(e) {} }
    var loader = btn.querySelector("i");
    if (loader) loader.style.animation = "spin 0.8s linear infinite";

    try {
        var params = getSliderValues();
        console.log("What-If params:", params);
        var result = await runWhatIfScenario(params);
        console.log("What-If result:", result);
        appState.scenario = result;

        var empty = $("#whatifEmpty"), results = $("#whatifResults");
        if (empty) empty.classList.add("hidden");
        if (results) results.classList.remove("hidden");

        var risk = calculateRisk(result.utilization);
        var simBaselineEl = $("#simBaseline"); if (simBaselineEl) simBaselineEl.textContent = formatNumber(result.baselinePeak) + " MW";
        var simPeakEl = $("#simPeak"); if (simPeakEl) simPeakEl.textContent = formatNumber(result.simulatedPeak) + " MW";

        var changeEl = $("#simChange"), prefix = result.change >= 0 ? "+" : "";
        if (changeEl) {
            changeEl.textContent = prefix + formatNumber(result.change) + " MW";
            changeEl.className = "result-change " + (result.change >= 0 ? "increase" : "decrease");
        }

        var simUtilEl = $("#simUtil"); if (simUtilEl) simUtilEl.textContent = result.utilization + "%";

        var statusEl = $("#simStatus");
        if (statusEl) {
            if (result.utilization > 100) { statusEl.textContent = "CAPACITY EXCEEDED"; statusEl.className = "result-status exceeded"; }
            else if (risk.class === "high") { statusEl.textContent = "HIGH UTILIZATION"; statusEl.className = "result-status warning"; }
            else { statusEl.textContent = "WITHIN CAPACITY"; statusEl.className = "result-status safe"; }
        }

        var impP = $("#impactPeak");
        if (impP) {
            impP.textContent = prefix + formatNumber(result.change) + " MW";
            impP.className = "impact-value " + (result.change >= 0 ? "negative" : "positive");
        }
        var margin = CONFIG.capacity - result.simulatedPeak;
        var impM = $("#impactMargin");
        if (impM) {
            impM.textContent = (margin >= 0 ? "+" : "") + formatNumber(margin) + " MW";
            impM.className = "impact-value " + (margin >= 0 ? "positive" : "negative");
        }
        var impS = $("#impactStatus");
        if (impS) {
            impS.textContent = risk.level;
            impS.className = "impact-value " + (risk.class === "critical" || risk.class === "high" ? "critical" : "");
        }

        renderWhatIfChart(result);
        showToast("Simulation complete", "success");
    } catch (err) {
        console.error("What-If simulation error:", err);
        showToast("Simulation failed: " + err.message, "error");
    } finally {
        btn.classList.remove("loading"); btn.disabled = false;
        btnSpan.textContent = "RUN SIMULATION";
        if (btnIcon) btnIcon.setAttribute("data-lucide", "play");
        if (loader) loader.style.animation = "";
        if (typeof lucide !== 'undefined') { try { lucide.createIcons({ nodes: [btn] }); } catch(e) {} }
    }
}


// =============================================
// 11. EVENT LISTENERS
// =============================================

function setupEventListeners() {
    // Mobile menu
    var menuBtn = $("#mobileMenuBtn"), sidebar = $("#sidebar"), overlay = $("#mobileOverlay");
    if (menuBtn) menuBtn.addEventListener("click", function () {
        sidebar.classList.toggle("open"); overlay.classList.toggle("visible");
    });
    if (overlay) overlay.addEventListener("click", function () {
        sidebar.classList.remove("open"); overlay.classList.remove("visible");
    });
    document.addEventListener("keydown", function (e) {
        if (e.key === "Escape" && sidebar) { sidebar.classList.remove("open"); if (overlay) overlay.classList.remove("visible"); }
    });

    // Refresh
    var refreshBtn = $("#refreshBtn");
    if (refreshBtn) refreshBtn.addEventListener("click", function () {
        showToast("Refreshing data\u2026", "info");
        initCurrentPage();
    });

    // VIEW GRID RISK button (overview page)
    var viewRiskBtn = $("#viewRiskBtn");
    if (viewRiskBtn) viewRiskBtn.addEventListener("click", function () { window.location.href = "risk.html"; });

    // Chart tabs (local toggle, no navigation)
    $$("[data-range]").forEach(function (tab) {
        tab.addEventListener("click", function () {
            tab.parentElement.querySelectorAll(".chart-tab").forEach(function (t) { t.classList.remove("active"); });
            tab.classList.add("active");
            showToast("Switched to " + tab.dataset.range.toUpperCase() + " view", "info");
        });
    });
    $$("[data-forecast-range]").forEach(function (tab) {
        tab.addEventListener("click", function () {
            tab.parentElement.querySelectorAll(".chart-tab").forEach(function (t) { t.classList.remove("active"); });
            tab.classList.add("active");
            showToast("Forecast range: " + tab.dataset.forecastRange.toUpperCase(), "info");
        });
    });

    // What-If sliders
    ["sliderTemp", "sliderHumidity", "sliderSolar", "sliderGrowth"].forEach(function (id) {
        var el = document.getElementById(id);
        if (el) el.addEventListener("input", updateSliderDisplay);
    });

    // Run Simulation
    var simBtn = $("#runSimBtn");
    if (simBtn) simBtn.addEventListener("click", executeSimulation);
}


// =============================================
// 12. PAGE-SPECIFIC INITIALIZATION
// =============================================

async function initCurrentPage() {
    var page = appState.currentPage;
    try {
        switch (page) {
            case "overview":
                var oData = await Promise.all([fetchForecast(), fetchWeather(), fetchRisk()]);
                appState.forecast = oData[0]; appState.weather = oData[1]; appState.risk = oData[2];
                updateOverviewDOMValues(oData[0], oData[1]);
                renderKPIs(oData[0], oData[2]);
                renderOverviewChart(oData[0]);
                renderDemandDrivers();
                renderAlerts();
                renderOffsetDonut(oData[1].solarGeneration, oData[0].peakDemand);
                renderWeatherSparkline();
                break;
            case "forecast":
                var fAll = await Promise.all([fetchForecast(), fetchMetrics()]);
                appState.forecast = fAll[0];
                updateForecastPageDOMValues(fAll[1]);
                renderForecastChart(fAll[0]);
                renderForecastTable(fAll[0]);
                break;
            case "risk":
                var rData = await fetchRisk();
                appState.risk = rData;
                renderRiskPage(rData);
                break;
            case "whatif":
                // Start by loading actual conditions to seed sliders and baseline
                var wiAll = await Promise.all([fetchForecast(), fetchWeather()]);
                appState.forecast = wiAll[0];
                appState.weather = wiAll[1];
                
                var sliderTemp = $("#sliderTemp"); if (sliderTemp) sliderTemp.value = wiAll[1].temperature;
                var sliderHum = $("#sliderHumidity"); if (sliderHum) sliderHum.value = wiAll[1].humidity;
                var sliderSol = $("#sliderSolar"); if (sliderSol) sliderSol.value = wiAll[1].solarGeneration;
                
                updateSliderDisplay();
                
                var simBaseline = $("#simBaseline"); if (simBaseline) simBaseline.textContent = formatNumber(wiAll[0].peakDemand) + " MW";
                var simUtil = $("#whatifBaselineUtil"); if (simUtil) simUtil.textContent = ((wiAll[0].peakDemand / CONFIG.capacity) * 100).toFixed(1) + "%";
                break;
            case "weather":
                var wAll = await Promise.all([fetchForecast(), fetchWeather()]);
                appState.forecast = wAll[0]; appState.weather = wAll[1];
                updateWeatherPageDOMValues(wAll[1]);
                renderWeatherTempChart(wAll[0]);
                renderDemandTempChart(wAll[0]);
                break;
            case "insights":
                var ins = await fetchInsights();
                appState.insights = ins;
                renderInsights(ins);
                break;
        }
        // Update last updated time
        var now = new Date();
        var lu = $("#lastUpdatedTime");
        if (lu) lu.textContent = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: false }) + " IST";
    } catch (err) {
        console.error("Failed to load page data:", err);
        showToast("Failed to load data. Please try again.", "error");
    }
}


// =============================================
// 13. MAIN INIT
// =============================================

function init() {
    buildAppShell();
    if (typeof lucide !== 'undefined') lucide.createIcons();
    updateDateTime();
    setInterval(updateDateTime, 1000);
    setupEventListeners();
    initCurrentPage();
}

document.addEventListener("DOMContentLoaded", init);
